# Generated by Django 4.0 on 2021-12-30 13:17
import string

from django.db import migrations, models

from products.models import Product


def gen_product(name: string, display_name: string, price: int, hit_count: int, review_count: int,
                review_point: int):
    product = Product(name=name, display_name=display_name, price=price, sale_price=price - 1000, hit_count=hit_count,
                      review_count=review_count, review_point=review_point)
    product.save()


def gen_master(apps, schema_editor):
    price = 10000
    hit_count = 1000
    review_count = 100
    review_point = 3

    gen_product('구두', '인스타 셀럽 구두', price, hit_count, review_count, review_point)
    gen_product('구두', '아이돌 구두', price + 2000, hit_count + 500, review_count + 50, review_point + 1)

    price = 12000
    hit_count = 2000
    review_count = 200
    review_point = 4

    gen_product('니트', '인스타 셀럽 니트', price, hit_count, review_count, review_point)
    gen_product('니트', '아이돌 니트', price + 2000, hit_count + 500, review_count + 50, review_point + 1)

    price = 14000
    hit_count = 2000
    review_count = 200
    review_point = 4

    gen_product('롱스커트', '인스타 셀럽 롱스커트', price, hit_count, review_count, review_point)
    gen_product('롱스커트', '아이돌 롱스커트', price + 2000,
                hit_count + 500, review_count + 50, review_point + 1)

    price = 10000
    hit_count = 1000
    review_count = 100
    review_point = 2

    gen_product('숏스커트', '인스타 셀럽 숏스커트', price, hit_count, review_count, review_point)
    gen_product('숏스커트', '아이돌 숏스커트', price + 2000, hit_count + 500, review_count + 50, review_point + 1)

    price = 20000
    hit_count = 1300
    review_count = 130
    review_point = 3

    gen_product('청바지', '인스타 셀럽 청바지', price, hit_count, review_count, review_point)
    gen_product('청바지', '아이돌 청바지', price + 2000, hit_count + 500, review_count + 50, review_point + 1)

    price = 30000
    hit_count = 1400
    review_count = 140
    review_point = 3

    gen_product('청자켓', '인스타 셀럽 청자켓', price, hit_count, review_count, review_point)
    gen_product('청자켓', '아이돌 청자켓', price + 2000, hit_count + 500, review_count + 50, review_point + 1)

    price = 15000
    hit_count = 700
    review_count = 50
    review_point = 2

    gen_product('청치마', '인스타 셀럽 청치마', price, hit_count, review_count, review_point)
    gen_product('청치마', '아이돌 청치마', price + 2000, hit_count + 500, review_count + 50, review_point + 1)

    price = 75000
    hit_count = 1700
    review_count = 150
    review_point = 4

    gen_product('코트', '인스타 셀럽 코트', price, hit_count, review_count, review_point)
    gen_product('코트', '아이돌 코트', price + 2000, hit_count + 500, review_count + 50, review_point + 1)

    price = 175000
    hit_count = 1800
    review_count = 190
    review_point = 4

    gen_product('백', '인스타 셀럽 백', price, hit_count, review_count, review_point)
    gen_product('백', '아이돌 백', price + 2000, hit_count + 500, review_count + 50, review_point + 1)

    price = 25000
    hit_count = 800
    review_count = 90
    review_point = 2

    gen_product('블라우스', '인스타 셀럽 블라우스', price, hit_count, review_count, review_point)
    gen_product('블라우스', '아이돌 블라우스', price + 2000, hit_count + 500, review_count + 50, review_point + 1)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='등록날짜')),
                ('name', models.CharField(max_length=100, verbose_name='내부상품명')),
                ('display_name', models.CharField(max_length=100, verbose_name='노출상품명')),
                ('price', models.PositiveIntegerField(verbose_name='권장판매가격')),
                ('sale_price', models.PositiveIntegerField(verbose_name='실제판매가격')),
                ('hit_count', models.PositiveIntegerField(verbose_name='조회수')),
                ('review_count', models.PositiveIntegerField(verbose_name='리뷰수')),
                ('review_point', models.PositiveIntegerField(verbose_name='리뷰평점')),
            ],
        ),
        migrations.RunPython(gen_master),
    ]
